# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "virjendb_prepareupdate"
description: write your description here
keywords:
  - virjendb
  - virus
  - genomics
tools:
  - "virjendb":
      description: "An integrative virus sequence database that connects researchers with publicly available virus sequence data and its metadata."
      homepage: "https://virjendb.org/"
      documentation: "https://github.com/maltesie/vjdb-clustering/README.md"
      tool_dev_url: "https://github.com/maltesie/vjdb-clustering"
      doi: "no DOI available"
      licence: ["Biopython License Agreement"] ## TODO @maltesie, please comment
      identifier: ""

input:
  - fna_gz:
      type: file
      description: GZipped FASTA nucleic acid file, containing new viral sequences
      pattern: "*.{fna.gz}"
      ontologies:
        - edam: http://edamontology.org/format_1929 # FASTA
  - reps_fna_gz:
      type: file
      description: GZipped FASTA nucleic acid file, containing representative viral sequences from initial clustering
      pattern: "*.{fna.gz}"
      ontologies:
        - edam: http://edamontology.org/format_1929 # FASTA
output:
  combined_reps_fna:
    - "*.fna.gz":
        type: file
        description: GZipped FASTA nucleic acid file, containing existing reps and the deduplicated (via hash) new reps
        pattern: "*.{fna.gz}"
        ontologies:
        - edam: http://edamontology.org/format_1929 # FASTA 
  hashed_reps:
    - "*.CSV":
        type: file
        description: CSV file containing the sequence ID, representative ID, GC content and length
        pattern: "*.{csv}"
        ontologies:
        - edam: http://edamontology.org/format_3752 # CSV 
  versions_biopython:
    - - ${task.process}:
          type: string
          description: The name of the process
      - biopython:
          type: string
          description: The name of the tool
      - python -c "import Bio; print(Bio.__version__)":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - biopython:
          type: string
          description: The name of the tool
      - python -c "import Bio; print(Bio.__version__)":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@akaviaLab"
maintainers:
  - "@akaviaLab"
