# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "virjendb_hashddeduplicate"
description: write your description here
keywords:
  - virjendb
  - virus
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "virjendb":
      description: "Freely available tools for computational molecular biology."
      homepage: "https://virjendb.org/"
      documentation: "https://github.com/maltesie/vjdb-clustering/README.md"
      tool_dev_url: "https://github.com/maltesie/vjdb-clustering"
      doi: "no DOI available"
      licence: ["Biopython License Agreement"] ## @maltesie, please comment
      identifier: ""

input:
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
      ontologies:
        - edam: http://edamontology.org/format_2572 # BAM
        - edam: http://edamontology.org/format_2573 # CRAM
        - edam: http://edamontology.org/format_3462 # SAM
output:
  bam:
    - "*.bam":
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: http://edamontology.org/format_2572 # BAM
          - edam: http://edamontology.org/format_2573 # CRAM
          - edam: http://edamontology.org/format_3462 # SAM
  versions_vjdb:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vjdb:
          type: string
          description: The name of the tool
      - vjdb --version:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vjdb:
          type: string
          description: The name of the tool
      - vjdb --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@akaviaLab"
maintainers:
  - "@akaviaLab"
